site_name: mdocs
theme: readthedocs
docs_dir: docs
copyright: Copyright (c) 2018 Makeblock Team

pages:
- TUTORIALS:
    - 'Introduction': 'index.md'
    - 'Hello, World!': 'tutorials/helloworld.md'
- API REFERENCE:
    - 'codey rocky Python API': 'api/codey.md'
    # - 'scratch 精灵图 ': 'api/scratch-sprite.md'
